import type { Match } from "./txline";

// Training-mode catalogue: real World Cup national teams and well-known
// players as a form guide, with simulated (made-up, not live) odds and
// results so the scoring engine can be practiced against instantly and
// repeatedly, independent of TxLINE's real fixture list.

export const TRAINING_MATCHES: Match[] = [
  {
    id: "training-arg-bra",
    competition: "Training Mode",
    homeTeam: "Argentina",
    awayTeam: "Brazil",
    kickoffISO: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: "finished",
    homeScore: 2,
    awayScore: 1,
    odds: { home: 2.3, draw: 3.2, away: 2.7 },
    homeLoadout: [
      "Emiliano Martínez",
      "Nahuel Molina",
      "Cristian Romero",
      "Nicolás Otamendi",
      "Nicolás Tagliafico",
      "Rodrigo De Paul",
      "Enzo Fernández",
      "Alexis Mac Allister",
      "Ángel Di María",
      "Lionel Messi",
      "Julián Álvarez",
    ],
    awayLoadout: [
      "Alisson",
      "Danilo",
      "Marquinhos",
      "Éder Militão",
      "Alex Sandro",
      "Casemiro",
      "Bruno Guimarães",
      "Lucas Paquetá",
      "Raphinha",
      "Vinícius Jr.",
      "Neymar",
    ],
    preview: [
      "The last time these two shared a pitch you could feel it through the screen — tonight promises exactly that kind of theatre.",
      "Messi drops deeper than ever these days, dictating tempo rather than chasing it. Watch how fast Brazil's midfield tries to close that pocket of space around him.",
      "Vinícius Jr. against Tagliafico down the left is the individual battle of the night — one explosive, one relentless, neither built to back down.",
      "Expect a feverish early tempo. Both benches are shouting before kickoff has even happened.",
    ],
  },
  {
    id: "training-fra-eng",
    competition: "Training Mode",
    homeTeam: "France",
    awayTeam: "England",
    kickoffISO: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
    status: "finished",
    homeScore: 1,
    awayScore: 1,
    odds: { home: 2.5, draw: 3.0, away: 2.9 },
    homeLoadout: [
      "Mike Maignan",
      "Jules Koundé",
      "Dayot Upamecano",
      "William Saliba",
      "Theo Hernández",
      "Aurélien Tchouaméni",
      "N'Golo Kanté",
      "Adrien Rabiot",
      "Ousmane Dembélé",
      "Kylian Mbappé",
      "Antoine Griezmann",
    ],
    awayLoadout: [
      "Jordan Pickford",
      "Kyle Walker",
      "John Stones",
      "Marc Guéhi",
      "Kieran Trippier",
      "Declan Rice",
      "Jude Bellingham",
      "Phil Foden",
      "Bukayo Saka",
      "Harry Kane",
      "Cole Palmer",
    ],
    preview: [
      "France come into this unbeaten in eleven, and Mbappé linking with Dembélé down the right has been the story of their tournament so far.",
      "England's answer is Bellingham — increasingly the heartbeat of this side, drifting between the lines wherever the game needs him most.",
      "Trippier against Dembélé is the flashpoint to watch early — a battle of experience versus searing pace down that flank.",
      "Both managers have kept their team news tight all week. Expect a cagey opening twenty minutes before anyone commits.",
    ],
  },
  {
    id: "training-esp-ger",
    competition: "Training Mode",
    homeTeam: "Spain",
    awayTeam: "Germany",
    kickoffISO: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    status: "finished",
    homeScore: 3,
    awayScore: 1,
    odds: { home: 2.1, draw: 3.4, away: 3.3 },
    homeLoadout: [
      "Unai Simón",
      "Dani Carvajal",
      "Robin Le Normand",
      "Aymeric Laporte",
      "Marc Cucurella",
      "Rodri",
      "Pedri",
      "Fabián Ruiz",
      "Nico Williams",
      "Álvaro Morata",
      "Lamine Yamal",
    ],
    awayLoadout: [
      "Manuel Neuer",
      "Joshua Kimmich",
      "Antonio Rüdiger",
      "Jonathan Tah",
      "David Raum",
      "Robert Andrich",
      "Toni Kroos",
      "Florian Wirtz",
      "Jamal Musiala",
      "Kai Havertz",
      "Leroy Sané",
    ],
    preview: [
      "Spain haven't lost in over a year, and it's Yamal — still a teenager — pulling the strings against defenses twice his age.",
      "Germany rebuild around Wirtz and Musiala's interplay, two of the most technically gifted attackers in the tournament sharing a pitch.",
      "Rüdiger against Nico Williams down that side is a genuine mismatch on paper — pace against power, and Spain will look to exploit it early and often.",
      "Spain to control the ball, Germany to counter through the lines — a classic contrast of styles, rarely settled by the letter of the script.",
    ],
  },
  {
    id: "training-por-ned",
    competition: "Training Mode",
    homeTeam: "Portugal",
    awayTeam: "Netherlands",
    kickoffISO: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(),
    status: "finished",
    homeScore: 0,
    awayScore: 2,
    odds: { home: 2.6, draw: 3.1, away: 2.6 },
    homeLoadout: ["Ronaldo", "Bruno Fernandes", "Bernardo Silva"],
    awayLoadout: ["Van Dijk", "Depay", "Gakpo"],
  },
  {
    id: "training-cro-mar",
    competition: "Training Mode",
    homeTeam: "Croatia",
    awayTeam: "Morocco",
    kickoffISO: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    status: "finished",
    homeScore: 1,
    awayScore: 2,
    odds: { home: 2.4, draw: 3.2, away: 2.9 },
    homeLoadout: ["Modrić", "Kovačić", "Perišić"],
    awayLoadout: ["Hakimi", "Ziyech", "En-Nesyri"],
  },
  {
    id: "training-bel-ita",
    competition: "Training Mode",
    homeTeam: "Belgium",
    awayTeam: "Italy",
    kickoffISO: new Date(Date.now() - 29 * 60 * 60 * 1000).toISOString(),
    status: "finished",
    homeScore: 2,
    awayScore: 2,
    odds: { home: 2.5, draw: 3.0, away: 2.9 },
    homeLoadout: ["De Bruyne", "Lukaku", "Doku"],
    awayLoadout: ["Chiesa", "Barella", "Donnarumma"],
  },
  {
    id: "training-uru-usa",
    competition: "Training Mode",
    homeTeam: "Uruguay",
    awayTeam: "USA",
    kickoffISO: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    status: "finished",
    homeScore: 1,
    awayScore: 0,
    odds: { home: 1.9, draw: 3.3, away: 4.2 },
    homeLoadout: ["Núñez", "Valverde", "Bentancur"],
    awayLoadout: ["Pulisic", "McKennie", "Weah"],
  },
  {
    id: "training-jpn-sen",
    competition: "Training Mode",
    homeTeam: "Japan",
    awayTeam: "Senegal",
    kickoffISO: new Date(Date.now() - 31 * 60 * 60 * 1000).toISOString(),
    status: "finished",
    homeScore: 2,
    awayScore: 0,
    odds: { home: 2.7, draw: 3.1, away: 2.5 },
    homeLoadout: ["Mitoma", "Kubo", "Endo"],
    awayLoadout: ["Mané", "Koulibaly", "Sarr"],
  },
];

// Implied win% from decimal odds, normalized so the three outcomes sum to 100.
export function impliedWinPct(match: Match): { home: number; draw: number; away: number } | null {
  if (!match.odds) return null;
  const raw = {
    home: 1 / match.odds.home,
    draw: 1 / match.odds.draw,
    away: 1 / match.odds.away,
  };
  const total = raw.home + raw.draw + raw.away;
  return {
    home: Math.round((raw.home / total) * 100),
    draw: Math.round((raw.draw / total) * 100),
    away: Math.round((raw.away / total) * 100),
  };
}
